package nuagenetworks

import (
    "errors"
    "log"
    "crypto/tls"
    "github.com/hashicorp/terraform/helper/schema"
    "github.com/hashicorp/terraform/terraform"
    vspk "github.com/tpretz/vspk-go/vspk/5.4.1"
    "github.com/nuagenetworks/go-bambou/bambou"
)

func Provider() terraform.ResourceProvider {
    return &schema.Provider{
        Schema: map[string]*schema.Schema{
            "enterprise": &schema.Schema{
                Type:        schema.TypeString,
                Required:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_ORGANIZATION", "csp"),
            },
            "vsd_endpoint": &schema.Schema{
                Type:        schema.TypeString,
                Required:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_ENDPOINT", nil),
            },
            "username": &schema.Schema{
                Type:        schema.TypeString,
                Optional:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_USERNAME", "csproot"),
            },
            "password": &schema.Schema{
                Type:        schema.TypeString,
                Optional:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_PASSWORD", "csproot"),
            },
            "certificate_path": &schema.Schema{
                Type:        schema.TypeString,
                Optional:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_CERTIFICATE_PATH", nil),
            },
            "key_path": &schema.Schema{
                Type:        schema.TypeString,
                Optional:    true,
                DefaultFunc: schema.EnvDefaultFunc("VSD_KEY_PATH", nil),
            },
        },
        ConfigureFunc: providerConfigure,
        DataSourcesMap: map[string]*schema.Resource{
            "nuagenetworks_nsg_patch_profile": dataSourceNSGPatchProfile(),
            "nuagenetworks_vnf_interface": dataSourceVNFInterface(),
            "nuagenetworks_performance_monitor": dataSourcePerformanceMonitor(),
            "nuagenetworks_vm_resync": dataSourceVMResync(),
            "nuagenetworks_vnf_domain_mapping": dataSourceVNFDomainMapping(),
            "nuagenetworks_shared_network_resource": dataSourceSharedNetworkResource(),
            "nuagenetworks_syslog_destination": dataSourceSyslogDestination(),
            "nuagenetworks_enterprise_secured_data": dataSourceEnterpriseSecuredData(),
            "nuagenetworks_statistics": dataSourceStatistics(),
            "nuagenetworks_ospf_instance": dataSourceOSPFInstance(),
            "nuagenetworks_ike_gateway": dataSourceIKEGateway(),
            "nuagenetworks_domain_fip_acl_template_entry": dataSourceDomainFIPAclTemplateEntry(),
            "nuagenetworks_dscp_forwarding_class_table": dataSourceDSCPForwardingClassTable(),
            "nuagenetworks_web_domain_name": dataSourceWebDomainName(),
            "nuagenetworks_bootstrap": dataSourceBootstrap(),
            "nuagenetworks_policy_object_group": dataSourcePolicyObjectGroup(),
            "nuagenetworks_auto_discover_cluster": dataSourceAutoDiscoverCluster(),
            "nuagenetworks_domain": dataSourceDomain(),
            "nuagenetworks_l4_service_group": dataSourceL4ServiceGroup(),
            "nuagenetworks_tca": dataSourceTCA(),
            "nuagenetworks_enterprise_profile": dataSourceEnterpriseProfile(),
            "nuagenetworks_ipv6_filter_profile": dataSourceIPv6FilterProfile(),
            "nuagenetworks_rate_limiter": dataSourceRateLimiter(),
            "nuagenetworks_license_status": dataSourceLicenseStatus(),
            "nuagenetworks_cloud_mgmt_system": dataSourceCloudMgmtSystem(),
            "nuagenetworks_overlay_address_pool": dataSourceOverlayAddressPool(),
            "nuagenetworks_vm_interface": dataSourceVMInterface(),
            "nuagenetworks_auto_discovered_gateway": dataSourceAutoDiscoveredGateway(),
            "nuagenetworks_host_interface": dataSourceHostInterface(),
            "nuagenetworks_bfd_session": dataSourceBFDSession(),
            "nuagenetworks_ike_gateway_profile": dataSourceIKEGatewayProfile(),
            "nuagenetworks_vcenter_hypervisor": dataSourceVCenterHypervisor(),
            "nuagenetworks_ike_subnet": dataSourceIKESubnet(),
            "nuagenetworks_qos": dataSourceQOS(),
            "nuagenetworks_global_metadata": dataSourceGlobalMetadata(),
            "nuagenetworks_c_translation_map": dataSourceCTranslationMap(),
            "nuagenetworks_vrs_address_range": dataSourceVRSAddressRange(),
            "nuagenetworks_nsg_info": dataSourceNSGInfo(),
            "nuagenetworks_policy_statement": dataSourcePolicyStatement(),
            "nuagenetworks_ns_gateway_monitor": dataSourceNSGatewayMonitor(),
            "nuagenetworks_permission": dataSourcePermission(),
            "nuagenetworks_container_interface": dataSourceContainerInterface(),
            "nuagenetworks_event_log": dataSourceEventLog(),
            "nuagenetworks_vsp": dataSourceVSP(),
            "nuagenetworks_vlan_template": dataSourceVLANTemplate(),
            "nuagenetworks_pat_mapper": dataSourcePATMapper(),
            "nuagenetworks_csnat_pool": dataSourceCSNATPool(),
            "nuagenetworks_mac_filter_profile": dataSourceMACFilterProfile(),
            "nuagenetworks_mirror_destination": dataSourceMirrorDestination(),
            "nuagenetworks_pg_expression": dataSourcePGExpression(),
            "nuagenetworks_group_key_encryption_profile": dataSourceGroupKeyEncryptionProfile(),
            "nuagenetworks_l2_domain": dataSourceL2Domain(),
            "nuagenetworks_infrastructure_evdf_profile": dataSourceInfrastructureEVDFProfile(),
            "nuagenetworks_network_layout": dataSourceNetworkLayout(),
            "nuagenetworks_ns_port_template": dataSourceNSPortTemplate(),
            "nuagenetworks_alarm": dataSourceAlarm(),
            "nuagenetworks_vpn_connection": dataSourceVPNConnection(),
            "nuagenetworks_key_server_monitor_seed": dataSourceKeyServerMonitorSeed(),
            "nuagenetworks_vcenter_data_center": dataSourceVCenterDataCenter(),
            "nuagenetworks_all_gateway": dataSourceAllGateway(),
            "nuagenetworks_firewall_rule": dataSourceFirewallRule(),
            "nuagenetworks_ike_gateway_config": dataSourceIKEGatewayConfig(),
            "nuagenetworks_static_route": dataSourceStaticRoute(),
            "nuagenetworks_bridge_interface": dataSourceBridgeInterface(),
            "nuagenetworks_spat_sources_pool": dataSourceSPATSourcesPool(),
            "nuagenetworks_redirection_target_template": dataSourceRedirectionTargetTemplate(),
            "nuagenetworks_dscp_forwarding_class_mapping": dataSourceDSCPForwardingClassMapping(),
            "nuagenetworks_aggregate_metadata": dataSourceAggregateMetadata(),
            "nuagenetworks_l2_domain_template": dataSourceL2DomainTemplate(),
            "nuagenetworks_subnet": dataSourceSubnet(),
            "nuagenetworks_ns_port": dataSourceNSPort(),
            "nuagenetworks_ip_filter_profile": dataSourceIPFilterProfile(),
            "nuagenetworks_infrastructure_vsc_profile": dataSourceInfrastructureVscProfile(),
            "nuagenetworks_ns_gateways_count": dataSourceNSGatewaysCount(),
            "nuagenetworks_port_mapping": dataSourcePortMapping(),
            "nuagenetworks_bulk_statistics": dataSourceBulkStatistics(),
            "nuagenetworks_infrastructure_config": dataSourceInfrastructureConfig(),
            "nuagenetworks_policy_decision": dataSourcePolicyDecision(),
            "nuagenetworks_user": dataSourceUser(),
            "nuagenetworks_duc_group": dataSourceDUCGroup(),
            "nuagenetworks_license": dataSourceLicense(),
            "nuagenetworks_vsd_component": dataSourceVSDComponent(),
            "nuagenetworks_ltestatistics": dataSourceLtestatistics(),
            "nuagenetworks_cos_remarking_policy": dataSourceCOSRemarkingPolicy(),
            "nuagenetworks_vrs_metrics": dataSourceVRSMetrics(),
            "nuagenetworks_shunt_link": dataSourceShuntLink(),
            "nuagenetworks_lte_information": dataSourceLTEInformation(),
            "nuagenetworks_dhcp_option": dataSourceDHCPOption(),
            "nuagenetworks_enterprise_network": dataSourceEnterpriseNetwork(),
            "nuagenetworks_p_translation_map": dataSourcePTranslationMap(),
            "nuagenetworks_ns_redundant_gateway_group": dataSourceNSRedundantGatewayGroup(),
            "nuagenetworks_zone_template": dataSourceZoneTemplate(),
            "nuagenetworks_key_server_member": dataSourceKeyServerMember(),
            "nuagenetworks_key_server_monitor_sek": dataSourceKeyServerMonitorSEK(),
            "nuagenetworks_saa_s_application_type": dataSourceSaaSApplicationType(),
            "nuagenetworks_command": dataSourceCommand(),
            "nuagenetworks_network_performance_binding": dataSourceNetworkPerformanceBinding(),
            "nuagenetworks_connectionendpoint": dataSourceConnectionendpoint(),
            "nuagenetworks_gateway_security": dataSourceGatewaySecurity(),
            "nuagenetworks_gateways_location": dataSourceGatewaysLocation(),
            "nuagenetworks_custom_property": dataSourceCustomProperty(),
            "nuagenetworks_routing_policy": dataSourceRoutingPolicy(),
            "nuagenetworks_application_binding": dataSourceApplicationBinding(),
            "nuagenetworks_gateway_template": dataSourceGatewayTemplate(),
            "nuagenetworks_qos_policer": dataSourceQosPolicer(),
            "nuagenetworks_underlay": dataSourceUnderlay(),
            "nuagenetworks_redirection_target": dataSourceRedirectionTarget(),
            "nuagenetworks_ldap_configuration": dataSourceLDAPConfiguration(),
            "nuagenetworks_enterprise": dataSourceEnterprise(),
            "nuagenetworks_wan_service": dataSourceWANService(),
            "nuagenetworks_site_info": dataSourceSiteInfo(),
            "nuagenetworks_br_connection": dataSourceBRConnection(),
            "nuagenetworks_vnf_interface_descriptor": dataSourceVNFInterfaceDescriptor(),
            "nuagenetworks_virtual_firewall_rule": dataSourceVirtualFirewallRule(),
            "nuagenetworks_avatar": dataSourceAvatar(),
            "nuagenetworks_key_server_monitor_encrypted_seed": dataSourceKeyServerMonitorEncryptedSeed(),
            "nuagenetworks_vsg_redundant_port": dataSourceVsgRedundantPort(),
            "nuagenetworks_sap_ingress_qo_s_profile": dataSourceSAPIngressQoSProfile(),
            "nuagenetworks_gateway_redundant_port": dataSourceGatewayRedundantPort(),
            "nuagenetworks_psnat_pool": dataSourcePSNATPool(),
            "nuagenetworks_policy_group_template": dataSourcePolicyGroupTemplate(),
            "nuagenetworks_virtual_firewall_policy": dataSourceVirtualFirewallPolicy(),
            "nuagenetworks_application": dataSourceApplication(),
            "nuagenetworks_egress_acl_template": dataSourceEgressACLTemplate(),
            "nuagenetworks_egress_adv_fwd_entry_template": dataSourceEgressAdvFwdEntryTemplate(),
            "nuagenetworks_metadata": dataSourceMetadata(),
            "nuagenetworks_wireless_port": dataSourceWirelessPort(),
            "nuagenetworks_ingress_adv_fwd_entry_template": dataSourceIngressAdvFwdEntryTemplate(),
            "nuagenetworks_proxy_arp_filter": dataSourceProxyARPFilter(),
            "nuagenetworks_redundant_port": dataSourceRedundantPort(),
            "nuagenetworks_link": dataSourceLink(),
            "nuagenetworks_nsg_routing_policy_binding": dataSourceNSGRoutingPolicyBinding(),
            "nuagenetworks_ssh_key": dataSourceSSHKey(),
            "nuagenetworks_demarcation_service": dataSourceDemarcationService(),
            "nuagenetworks_public_network_macro": dataSourcePublicNetworkMacro(),
            "nuagenetworks_deployment_failure": dataSourceDeploymentFailure(),
            "nuagenetworks_pspat_map": dataSourcePSPATMap(),
            "nuagenetworks_bgp_peer": dataSourceBGPPeer(),
            "nuagenetworks_vport_mirror": dataSourceVPortMirror(),
            "nuagenetworks_network_performance_measurement": dataSourceNetworkPerformanceMeasurement(),
            "nuagenetworks_download_progress": dataSourceDownloadProgress(),
            "nuagenetworks_ingress_acl_entry_template": dataSourceIngressACLEntryTemplate(),
            "nuagenetworks_nsg_upgrade_profile": dataSourceNSGUpgradeProfile(),
            "nuagenetworks_policy_group": dataSourcePolicyGroup(),
            "nuagenetworks_dscp_remarking_policy_table": dataSourceDSCPRemarkingPolicyTable(),
            "nuagenetworks_overlay_mirror_destination_template": dataSourceOverlayMirrorDestinationTemplate(),
            "nuagenetworks_policy_group_category": dataSourcePolicyGroupCategory(),
            "nuagenetworks_egress_profile": dataSourceEgressProfile(),
            "nuagenetworks_vcenter_cluster": dataSourceVCenterCluster(),
            "nuagenetworks_enterprise_security": dataSourceEnterpriseSecurity(),
            "nuagenetworks_duc_group_binding": dataSourceDUCGroupBinding(),
            "nuagenetworks_egress_adv_fwd_template": dataSourceEgressAdvFwdTemplate(),
            "nuagenetworks_zone": dataSourceZone(),
            "nuagenetworks_ns_port_info": dataSourceNSPortInfo(),
            "nuagenetworks_multi_cast_list": dataSourceMultiCastList(),
            "nuagenetworks_vnf_catalog": dataSourceVNFCatalog(),
            "nuagenetworks_container_resync": dataSourceContainerResync(),
            "nuagenetworks_system_config": dataSourceSystemConfig(),
            "nuagenetworks_multi_cast_channel_map": dataSourceMultiCastChannelMap(),
            "nuagenetworks_ssid_connection": dataSourceSSIDConnection(),
            "nuagenetworks_bgp_neighbor": dataSourceBGPNeighbor(),
            "nuagenetworks_vlan": dataSourceVLAN(),
            "nuagenetworks_auto_discover_hypervisor_from_cluster": dataSourceAutoDiscoverHypervisorFromCluster(),
            "nuagenetworks_dscp_remarking_policy": dataSourceDSCPRemarkingPolicy(),
            "nuagenetworks_statistics_policy": dataSourceStatisticsPolicy(),
            "nuagenetworks_zfb_request": dataSourceZFBRequest(),
            "nuagenetworks_overlay_management_subnet_profile": dataSourceOverlayManagementSubnetProfile(),
            "nuagenetworks_job": dataSourceJob(),
            "nuagenetworks_network_macro_group": dataSourceNetworkMacroGroup(),
            "nuagenetworks_ns_gateway_template": dataSourceNSGatewayTemplate(),
            "nuagenetworks_all_redundancy_group": dataSourceAllRedundancyGroup(),
            "nuagenetworks_patnat_pool": dataSourcePATNATPool(),
            "nuagenetworks_vport": dataSourceVPort(),
            "nuagenetworks_all_alarm": dataSourceAllAlarm(),
            "nuagenetworks_ns_gateway_summary": dataSourceNSGatewaySummary(),
            "nuagenetworks_captive_portal_profile": dataSourceCaptivePortalProfile(),
            "nuagenetworks_applicationperformancemanagementbinding": dataSourceApplicationperformancemanagementbinding(),
            "nuagenetworks_vsc": dataSourceVSC(),
            "nuagenetworks_forwarding_path_list": dataSourceForwardingPathList(),
            "nuagenetworks_l7applicationsignature": dataSourceL7applicationsignature(),
            "nuagenetworks_hsc": dataSourceHSC(),
            "nuagenetworks_user_context": dataSourceUserContext(),
            "nuagenetworks_vrs": dataSourceVRS(),
            "nuagenetworks_egress_qos_policy": dataSourceEgressQOSPolicy(),
            "nuagenetworks_group": dataSourceGroup(),
            "nuagenetworks_netconf_manager": dataSourceNetconfManager(),
            "nuagenetworks_address_range": dataSourceAddressRange(),
            "nuagenetworks_bgp_profile": dataSourceBGPProfile(),
            "nuagenetworks_ingress_adv_fwd_template": dataSourceIngressAdvFwdTemplate(),
            "nuagenetworks_location": dataSourceLocation(),
            "nuagenetworks_egress_acl_entry_template": dataSourceEgressACLEntryTemplate(),
            "nuagenetworks_netconf_session": dataSourceNetconfSession(),
            "nuagenetworks_l4_service": dataSourceL4Service(),
            "nuagenetworks_tier": dataSourceTier(),
            "nuagenetworks_ikepsk": dataSourceIKEPSK(),
            "nuagenetworks_port_template": dataSourcePortTemplate(),
            "nuagenetworks_multi_nic_vport": dataSourceMultiNICVPort(),
            "nuagenetworks_ike_encryptionprofile": dataSourceIKEEncryptionprofile(),
            "nuagenetworks_patch": dataSourcePatch(),
            "nuagenetworks_floating_ip": dataSourceFloatingIp(),
            "nuagenetworks_ospf_interface": dataSourceOSPFInterface(),
            "nuagenetworks_destinationurl": dataSourceDestinationurl(),
            "nuagenetworks_vcenter_eam_config": dataSourceVCenterEAMConfig(),
            "nuagenetworks_policy_entry": dataSourcePolicyEntry(),
            "nuagenetworks_ns_gateway": dataSourceNSGateway(),
            "nuagenetworks_enterprise_permission": dataSourceEnterprisePermission(),
            "nuagenetworks_web_category": dataSourceWebCategory(),
            "nuagenetworks_multi_cast_range": dataSourceMultiCastRange(),
            "nuagenetworks_pg_expression_template": dataSourcePGExpressionTemplate(),
            "nuagenetworks_domain_template": dataSourceDomainTemplate(),
            "nuagenetworks_monitorscope": dataSourceMonitorscope(),
            "nuagenetworks_trunk": dataSourceTrunk(),
            "nuagenetworks_netconf_profile": dataSourceNetconfProfile(),
            "nuagenetworks_nsg_group": dataSourceNSGGroup(),
            "nuagenetworks_forwarding_path_list_entry": dataSourceForwardingPathListEntry(),
            "nuagenetworks_vcenter": dataSourceVCenter(),
            "nuagenetworks_autodiscovereddatacenter": dataSourceAutodiscovereddatacenter(),
            "nuagenetworks_ingress_qos_policy": dataSourceIngressQOSPolicy(),
            "nuagenetworks_overlay_patnat_entry": dataSourceOverlayPATNATEntry(),
            "nuagenetworks_infrastructure_gateway_profile": dataSourceInfrastructureGatewayProfile(),
            "nuagenetworks_saa_s_application_group": dataSourceSaaSApplicationGroup(),
            "nuagenetworks_ingress_acl_template": dataSourceIngressACLTemplate(),
            "nuagenetworks_vrs_redeploymentpolicy": dataSourceVRSRedeploymentpolicy(),
            "nuagenetworks_vnf_threshold_policy": dataSourceVNFThresholdPolicy(),
            "nuagenetworks_vcenter_vrs_config": dataSourceVCenterVRSConfig(),
            "nuagenetworks_default_gateway": dataSourceDefaultGateway(),
            "nuagenetworks_vnf_descriptor": dataSourceVNFDescriptor(),
            "nuagenetworks_key_server_monitor": dataSourceKeyServerMonitor(),
            "nuagenetworks_ingress_profile": dataSourceIngressProfile(),
            "nuagenetworks_monitoring_port": dataSourceMonitoringPort(),
            "nuagenetworks_uplink_rd": dataSourceUplinkRD(),
            "nuagenetworks_uplink_connection": dataSourceUplinkConnection(),
            "nuagenetworks_zfb_auto_assignment": dataSourceZFBAutoAssignment(),
            "nuagenetworks_port": dataSourcePort(),
            "nuagenetworks_next_hop": dataSourceNextHop(),
            "nuagenetworks_redundancy_group": dataSourceRedundancyGroup(),
            "nuagenetworks_patip_entry": dataSourcePATIPEntry(),
            "nuagenetworks_vm": dataSourceVM(),
            "nuagenetworks_container": dataSourceContainer(),
            "nuagenetworks_virtual_ip": dataSourceVirtualIP(),
            "nuagenetworks_overlay_management_profile": dataSourceOverlayManagementProfile(),
            "nuagenetworks_applicationperformancemanagement": dataSourceApplicationperformancemanagement(),
            "nuagenetworks_infrastructure_access_profile": dataSourceInfrastructureAccessProfile(),
            "nuagenetworks_subnet_template": dataSourceSubnetTemplate(),
            "nuagenetworks_vnf_metadata": dataSourceVNFMetadata(),
            "nuagenetworks_ip_reservation": dataSourceIPReservation(),
            "nuagenetworks_ospf_area": dataSourceOSPFArea(),
            "nuagenetworks_firewall_acl": dataSourceFirewallAcl(),
            "nuagenetworks_stats_collector_info": dataSourceStatsCollectorInfo(),
            "nuagenetworks_domain_fip_acl_template": dataSourceDomainFIPAclTemplate(),
            "nuagenetworks_address_map": dataSourceAddressMap(),
            "nuagenetworks_overlay_mirror_destination": dataSourceOverlayMirrorDestination(),
            "nuagenetworks_gateway": dataSourceGateway(),
            "nuagenetworks_vnf": dataSourceVNF(),
            "nuagenetworks_ike_gateway_connection": dataSourceIKEGatewayConnection(),
            "nuagenetworks_gateway_secured_data": dataSourceGatewaySecuredData(),
            "nuagenetworks_cos_remarking_policy_table": dataSourceCOSRemarkingPolicyTable(),
            "nuagenetworks_sap_egress_qo_s_profile": dataSourceSAPEgressQoSProfile(),
            "nuagenetworks_ike_certificate": dataSourceIKECertificate(),
            "nuagenetworks_vsd": dataSourceVSD(),
            "nuagenetworks_nat_map_entry": dataSourceNATMapEntry(),
        },
        ResourcesMap: map[string]*schema.Resource{
            "nuagenetworks_nsg_patch_profile": resourceNSGPatchProfile(),
            "nuagenetworks_performance_monitor": resourcePerformanceMonitor(),
            "nuagenetworks_vm_resync": resourceVMResync(),
            "nuagenetworks_vnf_domain_mapping": resourceVNFDomainMapping(),
            "nuagenetworks_shared_network_resource": resourceSharedNetworkResource(),
            "nuagenetworks_syslog_destination": resourceSyslogDestination(),
            "nuagenetworks_enterprise_secured_data": resourceEnterpriseSecuredData(),
            "nuagenetworks_ospf_instance": resourceOSPFInstance(),
            "nuagenetworks_ike_gateway": resourceIKEGateway(),
            "nuagenetworks_domain_fip_acl_template_entry": resourceDomainFIPAclTemplateEntry(),
            "nuagenetworks_dscp_forwarding_class_table": resourceDSCPForwardingClassTable(),
            "nuagenetworks_web_domain_name": resourceWebDomainName(),
            "nuagenetworks_policy_object_group": resourcePolicyObjectGroup(),
            "nuagenetworks_domain": resourceDomain(),
            "nuagenetworks_l4_service_group": resourceL4ServiceGroup(),
            "nuagenetworks_tca": resourceTCA(),
            "nuagenetworks_enterprise_profile": resourceEnterpriseProfile(),
            "nuagenetworks_rate_limiter": resourceRateLimiter(),
            "nuagenetworks_cloud_mgmt_system": resourceCloudMgmtSystem(),
            "nuagenetworks_overlay_address_pool": resourceOverlayAddressPool(),
            "nuagenetworks_vm_interface": resourceVMInterface(),
            "nuagenetworks_host_interface": resourceHostInterface(),
            "nuagenetworks_bfd_session": resourceBFDSession(),
            "nuagenetworks_ike_gateway_profile": resourceIKEGatewayProfile(),
            "nuagenetworks_vcenter_hypervisor": resourceVCenterHypervisor(),
            "nuagenetworks_ike_subnet": resourceIKESubnet(),
            "nuagenetworks_qos": resourceQOS(),
            "nuagenetworks_global_metadata": resourceGlobalMetadata(),
            "nuagenetworks_c_translation_map": resourceCTranslationMap(),
            "nuagenetworks_vrs_address_range": resourceVRSAddressRange(),
            "nuagenetworks_policy_statement": resourcePolicyStatement(),
            "nuagenetworks_permission": resourcePermission(),
            "nuagenetworks_container_interface": resourceContainerInterface(),
            "nuagenetworks_bootstrap_activation": resourceBootstrapActivation(),
            "nuagenetworks_vlan_template": resourceVLANTemplate(),
            "nuagenetworks_pat_mapper": resourcePATMapper(),
            "nuagenetworks_csnat_pool": resourceCSNATPool(),
            "nuagenetworks_mirror_destination": resourceMirrorDestination(),
            "nuagenetworks_pg_expression": resourcePGExpression(),
            "nuagenetworks_l2_domain": resourceL2Domain(),
            "nuagenetworks_infrastructure_evdf_profile": resourceInfrastructureEVDFProfile(),
            "nuagenetworks_ns_port_template": resourceNSPortTemplate(),
            "nuagenetworks_alarm": resourceAlarm(),
            "nuagenetworks_vpn_connection": resourceVPNConnection(),
            "nuagenetworks_key_server_monitor_seed": resourceKeyServerMonitorSeed(),
            "nuagenetworks_vcenter_data_center": resourceVCenterDataCenter(),
            "nuagenetworks_firewall_rule": resourceFirewallRule(),
            "nuagenetworks_static_route": resourceStaticRoute(),
            "nuagenetworks_bridge_interface": resourceBridgeInterface(),
            "nuagenetworks_spat_sources_pool": resourceSPATSourcesPool(),
            "nuagenetworks_redirection_target_template": resourceRedirectionTargetTemplate(),
            "nuagenetworks_dscp_forwarding_class_mapping": resourceDSCPForwardingClassMapping(),
            "nuagenetworks_l2_domain_template": resourceL2DomainTemplate(),
            "nuagenetworks_subnet": resourceSubnet(),
            "nuagenetworks_ns_port": resourceNSPort(),
            "nuagenetworks_infrastructure_vsc_profile": resourceInfrastructureVscProfile(),
            "nuagenetworks_user": resourceUser(),
            "nuagenetworks_duc_group": resourceDUCGroup(),
            "nuagenetworks_license": resourceLicense(),
            "nuagenetworks_cos_remarking_policy": resourceCOSRemarkingPolicy(),
            "nuagenetworks_shunt_link": resourceShuntLink(),
            "nuagenetworks_dhcp_option": resourceDHCPOption(),
            "nuagenetworks_enterprise_network": resourceEnterpriseNetwork(),
            "nuagenetworks_p_translation_map": resourcePTranslationMap(),
            "nuagenetworks_ns_redundant_gateway_group": resourceNSRedundantGatewayGroup(),
            "nuagenetworks_zone_template": resourceZoneTemplate(),
            "nuagenetworks_key_server_member": resourceKeyServerMember(),
            "nuagenetworks_key_server_monitor_sek": resourceKeyServerMonitorSEK(),
            "nuagenetworks_saa_s_application_type": resourceSaaSApplicationType(),
            "nuagenetworks_command": resourceCommand(),
            "nuagenetworks_network_performance_binding": resourceNetworkPerformanceBinding(),
            "nuagenetworks_connectionendpoint": resourceConnectionendpoint(),
            "nuagenetworks_custom_property": resourceCustomProperty(),
            "nuagenetworks_routing_policy": resourceRoutingPolicy(),
            "nuagenetworks_application_binding": resourceApplicationBinding(),
            "nuagenetworks_gateway_template": resourceGatewayTemplate(),
            "nuagenetworks_qos_policer": resourceQosPolicer(),
            "nuagenetworks_underlay": resourceUnderlay(),
            "nuagenetworks_redirection_target": resourceRedirectionTarget(),
            "nuagenetworks_enterprise": resourceEnterprise(),
            "nuagenetworks_wan_service": resourceWANService(),
            "nuagenetworks_site_info": resourceSiteInfo(),
            "nuagenetworks_br_connection": resourceBRConnection(),
            "nuagenetworks_vnf_interface_descriptor": resourceVNFInterfaceDescriptor(),
            "nuagenetworks_virtual_firewall_rule": resourceVirtualFirewallRule(),
            "nuagenetworks_avatar": resourceAvatar(),
            "nuagenetworks_key_server_monitor_encrypted_seed": resourceKeyServerMonitorEncryptedSeed(),
            "nuagenetworks_vsg_redundant_port": resourceVsgRedundantPort(),
            "nuagenetworks_gateway_redundant_port": resourceGatewayRedundantPort(),
            "nuagenetworks_psnat_pool": resourcePSNATPool(),
            "nuagenetworks_policy_group_template": resourcePolicyGroupTemplate(),
            "nuagenetworks_virtual_firewall_policy": resourceVirtualFirewallPolicy(),
            "nuagenetworks_application": resourceApplication(),
            "nuagenetworks_egress_acl_template": resourceEgressACLTemplate(),
            "nuagenetworks_egress_adv_fwd_entry_template": resourceEgressAdvFwdEntryTemplate(),
            "nuagenetworks_metadata": resourceMetadata(),
            "nuagenetworks_wireless_port": resourceWirelessPort(),
            "nuagenetworks_ingress_adv_fwd_entry_template": resourceIngressAdvFwdEntryTemplate(),
            "nuagenetworks_proxy_arp_filter": resourceProxyARPFilter(),
            "nuagenetworks_redundant_port": resourceRedundantPort(),
            "nuagenetworks_link": resourceLink(),
            "nuagenetworks_nsg_routing_policy_binding": resourceNSGRoutingPolicyBinding(),
            "nuagenetworks_ssh_key": resourceSSHKey(),
            "nuagenetworks_demarcation_service": resourceDemarcationService(),
            "nuagenetworks_public_network_macro": resourcePublicNetworkMacro(),
            "nuagenetworks_deployment_failure": resourceDeploymentFailure(),
            "nuagenetworks_pspat_map": resourcePSPATMap(),
            "nuagenetworks_vport_mirror": resourceVPortMirror(),
            "nuagenetworks_network_performance_measurement": resourceNetworkPerformanceMeasurement(),
            "nuagenetworks_ingress_acl_entry_template": resourceIngressACLEntryTemplate(),
            "nuagenetworks_nsg_upgrade_profile": resourceNSGUpgradeProfile(),
            "nuagenetworks_policy_group": resourcePolicyGroup(),
            "nuagenetworks_dscp_remarking_policy_table": resourceDSCPRemarkingPolicyTable(),
            "nuagenetworks_overlay_mirror_destination_template": resourceOverlayMirrorDestinationTemplate(),
            "nuagenetworks_policy_group_category": resourcePolicyGroupCategory(),
            "nuagenetworks_egress_profile": resourceEgressProfile(),
            "nuagenetworks_vcenter_cluster": resourceVCenterCluster(),
            "nuagenetworks_duc_group_binding": resourceDUCGroupBinding(),
            "nuagenetworks_egress_adv_fwd_template": resourceEgressAdvFwdTemplate(),
            "nuagenetworks_zone": resourceZone(),
            "nuagenetworks_container_resync": resourceContainerResync(),
            "nuagenetworks_multi_cast_channel_map": resourceMultiCastChannelMap(),
            "nuagenetworks_ssid_connection": resourceSSIDConnection(),
            "nuagenetworks_bgp_neighbor": resourceBGPNeighbor(),
            "nuagenetworks_vlan": resourceVLAN(),
            "nuagenetworks_dscp_remarking_policy": resourceDSCPRemarkingPolicy(),
            "nuagenetworks_statistics_policy": resourceStatisticsPolicy(),
            "nuagenetworks_zfb_request": resourceZFBRequest(),
            "nuagenetworks_overlay_management_subnet_profile": resourceOverlayManagementSubnetProfile(),
            "nuagenetworks_job": resourceJob(),
            "nuagenetworks_network_macro_group": resourceNetworkMacroGroup(),
            "nuagenetworks_ns_gateway_template": resourceNSGatewayTemplate(),
            "nuagenetworks_all_redundancy_group": resourceAllRedundancyGroup(),
            "nuagenetworks_patnat_pool": resourcePATNATPool(),
            "nuagenetworks_vport": resourceVPort(),
            "nuagenetworks_captive_portal_profile": resourceCaptivePortalProfile(),
            "nuagenetworks_applicationperformancemanagementbinding": resourceApplicationperformancemanagementbinding(),
            "nuagenetworks_forwarding_path_list": resourceForwardingPathList(),
            "nuagenetworks_egress_qos_policy": resourceEgressQOSPolicy(),
            "nuagenetworks_group": resourceGroup(),
            "nuagenetworks_netconf_manager": resourceNetconfManager(),
            "nuagenetworks_address_range": resourceAddressRange(),
            "nuagenetworks_bgp_profile": resourceBGPProfile(),
            "nuagenetworks_ingress_adv_fwd_template": resourceIngressAdvFwdTemplate(),
            "nuagenetworks_egress_acl_entry_template": resourceEgressACLEntryTemplate(),
            "nuagenetworks_netconf_session": resourceNetconfSession(),
            "nuagenetworks_l4_service": resourceL4Service(),
            "nuagenetworks_ikepsk": resourceIKEPSK(),
            "nuagenetworks_port_template": resourcePortTemplate(),
            "nuagenetworks_ike_encryptionprofile": resourceIKEEncryptionprofile(),
            "nuagenetworks_floating_ip": resourceFloatingIp(),
            "nuagenetworks_ospf_interface": resourceOSPFInterface(),
            "nuagenetworks_destinationurl": resourceDestinationurl(),
            "nuagenetworks_policy_entry": resourcePolicyEntry(),
            "nuagenetworks_ns_gateway": resourceNSGateway(),
            "nuagenetworks_enterprise_permission": resourceEnterprisePermission(),
            "nuagenetworks_web_category": resourceWebCategory(),
            "nuagenetworks_multi_cast_range": resourceMultiCastRange(),
            "nuagenetworks_pg_expression_template": resourcePGExpressionTemplate(),
            "nuagenetworks_domain_template": resourceDomainTemplate(),
            "nuagenetworks_monitorscope": resourceMonitorscope(),
            "nuagenetworks_trunk": resourceTrunk(),
            "nuagenetworks_netconf_profile": resourceNetconfProfile(),
            "nuagenetworks_nsg_group": resourceNSGGroup(),
            "nuagenetworks_forwarding_path_list_entry": resourceForwardingPathListEntry(),
            "nuagenetworks_vcenter": resourceVCenter(),
            "nuagenetworks_ingress_qos_policy": resourceIngressQOSPolicy(),
            "nuagenetworks_overlay_patnat_entry": resourceOverlayPATNATEntry(),
            "nuagenetworks_infrastructure_gateway_profile": resourceInfrastructureGatewayProfile(),
            "nuagenetworks_saa_s_application_group": resourceSaaSApplicationGroup(),
            "nuagenetworks_ingress_acl_template": resourceIngressACLTemplate(),
            "nuagenetworks_vrs_redeploymentpolicy": resourceVRSRedeploymentpolicy(),
            "nuagenetworks_vnf_threshold_policy": resourceVNFThresholdPolicy(),
            "nuagenetworks_vnf_descriptor": resourceVNFDescriptor(),
            "nuagenetworks_ingress_profile": resourceIngressProfile(),
            "nuagenetworks_uplink_connection": resourceUplinkConnection(),
            "nuagenetworks_zfb_auto_assignment": resourceZFBAutoAssignment(),
            "nuagenetworks_port": resourcePort(),
            "nuagenetworks_next_hop": resourceNextHop(),
            "nuagenetworks_redundancy_group": resourceRedundancyGroup(),
            "nuagenetworks_patip_entry": resourcePATIPEntry(),
            "nuagenetworks_vm": resourceVM(),
            "nuagenetworks_container": resourceContainer(),
            "nuagenetworks_virtual_ip": resourceVirtualIP(),
            "nuagenetworks_overlay_management_profile": resourceOverlayManagementProfile(),
            "nuagenetworks_applicationperformancemanagement": resourceApplicationperformancemanagement(),
            "nuagenetworks_infrastructure_access_profile": resourceInfrastructureAccessProfile(),
            "nuagenetworks_subnet_template": resourceSubnetTemplate(),
            "nuagenetworks_vnf_metadata": resourceVNFMetadata(),
            "nuagenetworks_ip_reservation": resourceIPReservation(),
            "nuagenetworks_ospf_area": resourceOSPFArea(),
            "nuagenetworks_firewall_acl": resourceFirewallAcl(),
            "nuagenetworks_certificate": resourceCertificate(),
            "nuagenetworks_domain_fip_acl_template": resourceDomainFIPAclTemplate(),
            "nuagenetworks_address_map": resourceAddressMap(),
            "nuagenetworks_overlay_mirror_destination": resourceOverlayMirrorDestination(),
            "nuagenetworks_gateway": resourceGateway(),
            "nuagenetworks_vnf": resourceVNF(),
            "nuagenetworks_ike_gateway_connection": resourceIKEGatewayConnection(),
            "nuagenetworks_gateway_secured_data": resourceGatewaySecuredData(),
            "nuagenetworks_cos_remarking_policy_table": resourceCOSRemarkingPolicyTable(),
            "nuagenetworks_ike_certificate": resourceIKECertificate(),
            "nuagenetworks_nat_map_entry": resourceNATMapEntry(),
        },
    }
}

func providerConfigure(d *schema.ResourceData) (root interface{}, err error) {
    // if we have a certificate path, we use cert auth
    log.Println("[INFO] Initializing Nuage Networks VSD client")

    var s *bambou.Session

    if certPathRaw, certPathOk := d.GetOk("certificate_path"); certPathOk {
      cert, tlsErr := tls.LoadX509KeyPair(certPathRaw.(string), d.Get("key_path").(string))
      if tlsErr != nil {
          return nil, errors.New("Error loading VSD generated certificates to authenticate with VSD: " + tlsErr.Error())
      }
      s, root = vspk.NewX509Session(&cert, d.Get("vsd_endpoint").(string))
    } else {
      s, root = vspk.NewSession(d.Get("username").(string), d.Get("password").(string), d.Get("enterprise").(string), d.Get("vsd_endpoint").(string))
    }

    berr := s.Start()

    if berr != nil {
        err = errors.New("Unable to connect to Nuage VSD: " + berr.Description)
        return
    }

    log.Println("[INFO] Nuage Networks VSD client initialized")

    return
}